
(function () {
"use strict";
var tg = window.Telegram && window.Telegram.WebApp;
var icons = {
 home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
 crown:'<path d="m2 8 5 4 5-8 5 8 5-4-2 12H4L2 8z"/><path d="M5 17h14"/>',
 profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
 arrow:'<path d="m9 18 6-6-6-6"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
 gift:'<rect x="3" y="9" width="18" height="12" rx="2"/><path d="M12 9v12M3 13h18M12 9c-3-6-9-5-7-1 1 2 7 1 7 1zm0 0c3-6 9-5 7-1-1 2-7 1-7 1z"/>',
 share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.7 10.6 6.6-4.2m-6.6 7 6.6 4.1"/>',
 copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
 check:'<path d="m4 12 5 5L20 6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5z"/>',
 shield:'<path d="m12 22 7-4V6l-7-4-7 4v12z"/><path d="m9 12 2 2 4-4"/>',
 info:'<circle cx="12" cy="12" r="10"/><path d="M12 11v6M12 7h.01"/>',
 wallet:'<rect x="2" y="5" width="20" height="15" rx="3"/><path d="M2 9h20M16 15h3"/>',
 settings:'<path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path d="M20 12a8 8 0 0 0-.2-1.8l2-1.4-2-3.4-2.3 1a8 8 0 0 0-3.1-1.8L14 2h-4l-.4 2.6a8 8 0 0 0-3.1 1.8l-2.3-1-2 3.4 2 1.4A8 8 0 0 0 4 12c0 .6.1 1.2.2 1.8l-2 1.4 2 3.4 2.3-1a8 8 0 0 0 3.1 1.8L10 22h4l.4-2.6a8 8 0 0 0 3.1-1.8l2.3 1 2-3.4-2-1.4c.1-.6.2-1.2.2-1.8z"/>',
 logout:'<path d="M10 17l5-5-5-5M15 12H3"/><path d="M12 3h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7"/>',
 star:'<path d="m12 2 3.1 6.4L22 9.4l-5 4.9 1.2 7-6.2-3.3-6.2 3.3 1.2-7-5-4.9 6.9-1z"/>',
 edit:'<path d="M12 20h9M4 16.5l11-11 4 4-11 11H4v-4zM16 4.5l4 4"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 refresh:'<path d="M21 11a9 9 0 0 0-16-5L2 9m0-6v6h6M3 13a9 9 0 0 0 16 5l3-3m0 6v-6h-6"/>',
 bolt:'<path d="m13 2-9 12h7l-1 8 10-12h-7z"/>',
 external:'<path d="M14 3h7v7M21 3l-10 10"/><path d="M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6"/>'
};
function icon(n){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[n]||icons.spark)+'</svg>';}
function esc(s){return String(s == null ? '' : s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function n(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:0});}
function fmtDate(ms){return ms ? new Date(ms).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';}
function avatar(user,cls){var name=(user.name||user.firstName||'G').trim();return '<div class="'+(cls||'user-avatar')+'">'+(user.photoUrl ? '<img src="'+esc(user.photoUrl)+'" alt="">' : esc(name.charAt(0).toUpperCase()))+'</div>';}
var state={page:'home',data:null,token:sessionStorage.getItem('afglion_session')||'',demo:!tg || !tg.initData,loading:false,admin:null,adminTab:'overview',configMissing:false};
var demoUser={id:'000000000',name:'Guest Member',username:'',photoUrl:'',balance:0,totalEarned:0,totalDeposited:0,totalWithdrawn:0,pendingWithdraw:0,vipActivatedAt:0,vipDaysClaimed:0,vipLastClaimSlot:0,referralCount:0,referralEarned:0,vipTier:'free',vipUntil:0,joinedAt:Date.now(),claimStreak:0,lastClaimAt:0,isAdmin:false};
var demoData={user:demoUser,referrals:[],transactions:[],settings:{appName:'AFGLION',dailyBonus:1,referralPercent:10,minDeposit:50,minWithdraw:100,botUsername:'Afglionbot',announcement:'Welcome to AFGLION.',depositInstructions:'Deposit requests are reviewed manually.',payoutInstructions:'Withdrawals are reviewed manually.',plans:{gold:{name:'Gold VIP',price:500,dailyReward:50,days:30},elite:{name:'Elite VIP',price:1000,dailyReward:110,days:30}}},vipRequest:null,activity:[]};
var root=document.getElementById('app');
function toast(message){var el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show');},2900);try{tg&&tg.HapticFeedback&&tg.HapticFeedback.notificationOccurred('success');}catch(e){}}
function user(){return (state.data||demoData).user;}
function data(){return state.data||demoData;}
function goldTitle(title,desc){return '<div class="page-intro"><div class="eyebrow">AFGLION EXCLUSIVE</div><h1 class="page-title">'+title+'</h1><p class="body-sub">'+desc+'</p></div>';}
function section(t,action,label){return '<div class="section-head"><h2>'+t+'</h2>'+(action?'<button class="text-button" data-action="'+action+'">'+(label||'View all')+icon('arrow')+'</button>':'')+'</div>';}
function header(){return '<header class="topbar"><div class="brand-wrap"><span class="brand-mark">V</span><div><div class="brand-name">AFGLION</div><div class="brand-kicker">MEMBERS CLUB</div></div></div><div class="header-tools"><button class="round-button" data-action="notification" aria-label="Notifications">'+icon('bell')+'</button><button class="avatar-button" data-page="profile" aria-label="Open profile">'+avatar(user(),'') .replace('class=""','class="header-avatar"')+'</button></div></header>';}
function nav(){return '<nav class="bottom-nav" aria-label="Main navigation">'+[
 ['home','home','Home'],['referral','users','Referral'],['vip','crown','VIP'],['profile','profile','Profile']
].map(function(v){return '<button class="nav-item '+(state.page===v[0]?'active':'')+'" data-page="'+v[0]+'" aria-label="'+v[2]+'">'+icon(v[1])+'<span>'+v[2]+'</span></button>';}).join('')+'</nav>';}

function currency(v){return n(v)+' AFN';}
function activePlan(){var u=user(),p=(data().settings.plans||{})[u.vipTier];return p&&u.vipUntil>Date.now()-86400000?p:null;}
function vipSlot(){var u=user(),p=activePlan();return p&&u.vipActivatedAt?Math.min(p.days,Math.floor((Date.now()-u.vipActivatedAt)/86400000)):0;}
function vipCanClaim(){var u=user(),p=activePlan(),slot=vipSlot();return !!(p&&slot>=1&&slot>(u.vipLastClaimSlot||0)&&(u.vipDaysClaimed||0)<p.days&&Date.now()<=u.vipUntil+86400000);}
function hero(){var u=user();return '<div class="hero"><div class="hero-label">AVAILABLE BALANCE</div><div class="hero-amount">'+n(u.balance)+' <span class="hero-unit">AFN</span></div><div style="font-size:11px;opacity:.78;font-weight:700">Your secure in-app wallet</div><div class="hero-foot"><div class="hero-tag"><span></span> MANUAL PAYMENTS</div><div class="hero-stamp">'+esc((u.vipTier||'free').toUpperCase())+' MEMBER</div></div></div>';}
function earningsCard(){var u=user(),s=data().settings,p=activePlan();return '<div class="earning-card"><div class="earning-top"><div><span class="eyebrow">VIP EARNINGS</span><h3>'+(p?currency(p.dailyReward)+' / day':'Activate VIP rewards')+'</h3><p>'+(p?'Claim each eligible day · '+n(u.vipDaysClaimed||0)+' claimed / '+n(p.days)+' days':'Choose your VIP plan from the membership page')+'</p></div><div class="round-icon">'+icon('crown')+'</div></div>'+(p?'<button class="btn btn-primary btn-block" data-action="vip-claim" '+(!vipCanClaim()?'disabled':'')+'>'+(vipCanClaim()?'Claim VIP reward':'Next reward not ready')+'</button>':'<button class="btn btn-outline btn-block" data-page="vip">View VIP plans '+icon('arrow')+'</button>')+'</div>';}
function home(){var u=user(),s=data().settings,available=Date.now()-(u.lastClaimAt||0)>=86400000,remaining=Math.max(0,Math.ceil((86400000-(Date.now()-(u.lastClaimAt||0)))/3600000));
return '<div class="view"><div class="greeting">Welcome back, <b>'+esc((u.name||'Member').split(' ')[0])+' ✨</b></div><h1 class="page-title" style="font-size:25px;margin:6px 0 22px">Build your future.</h1>'+hero()+
'<div class="wallet-actions"><button class="wallet-action" data-action="deposit"><span>'+icon('arrow')+'</span><b>Deposit</b><small>Manual top up</small></button><button class="wallet-action" data-action="withdraw"><span>'+icon('wallet')+'</span><b>Withdraw</b><small>Request payout</small></button><button class="wallet-action" data-page="wallet"><span>'+icon('clock')+'</span><b>History</b><small>My wallet</small></button></div>'+
'<div class="stats-row"><div class="stat-small"><div class="label">Rewards earned</div><div class="value">'+n(u.totalEarned)+'</div></div><div class="stat-small"><div class="label">Invited</div><div class="value">'+n(u.referralCount)+'</div></div><div class="stat-small"><div class="label">VIP plan</div><div class="value gold" style="text-transform:capitalize;font-size:17px">'+esc(u.vipTier||'free')+'</div></div></div>'+
section('Free earning · Daily check-in')+'<div class="daily-card"><div class="daily-left"><div class="daily-icon">'+icon('gift')+'</div><div><div class="daily-title">Daily check-in</div><div class="daily-sub">'+(available?'Claim '+currency(s.dailyBonus)+' today':'Next claim in ~'+remaining+'h')+'</div></div></div><button class="btn btn-primary btn-small" data-action="claim" '+(!available?'disabled':'')+'>'+(available?'Claim':'Claimed')+'</button></div>'+
section('VIP earnings')+earningsCard()+
section('Explore AFGLION')+'<div class="action-grid"><button class="action-tile" data-page="referral"><span class="action-icon">'+icon('users')+'</span><div><div class="action-title">Referral commissions</div><div class="action-desc">Earn '+n(s.referralPercent)+'% when friends purchase VIP.</div></div></button><button class="action-tile" data-page="vip"><span class="action-icon blue">'+icon('crown')+'</span><div><div class="action-title">VIP plans</div><div class="action-desc">Flexible rates and durations, admin managed.</div></div></button></div>'+
section('Latest updates')+'<div class="notice"><div class="notice-icon">'+icon('bell')+'</div><div><h3>AFGLION updates</h3><p>'+esc(s.announcement||'Welcome to AFGLION.')+'</p></div></div>'+footer()+'</div>';}
function referral(){var u=user(),s=data().settings,invitation=link(),pct=s.referralPercent||0,example=((s.plans||{}).gold||{}).price||500;return '<div class="view">'+goldTitle('Refer & earn.','Invite friends to AFGLION and receive a commission when their VIP purchase is approved.')+
'<div class="ref-visual"><div class="ref-symbol">'+icon('share')+'</div><h2>'+n(pct)+'% Referral Commission</h2><p>Commission applies to an approved, paid VIP purchase—not to an account signup.</p><div class="invite-pill">'+icon('spark')+' Example: '+n(Math.floor(example*pct/100))+' AFN on a '+n(example)+' AFN VIP purchase</div></div>'+
'<div class="stats-row"><div class="stat-small"><div class="label">Invited</div><div class="value">'+n(u.referralCount)+'</div></div><div class="stat-small"><div class="label">Commission</div><div class="value gold">'+n(u.referralEarned)+'</div></div><div class="stat-small"><div class="label">Rate</div><div class="value">'+n(pct)+'%</div></div></div>'+
section('Your invitation link')+'<div class="ref-linkbox"><span class="ref-url">'+esc(invitation||'Referral link available after bot setup')+'</span><button class="btn btn-primary btn-small" data-action="copy-ref" '+(!invitation?'disabled':'')+'>'+icon('copy')+' Copy</button></div>'+
'<button class="btn btn-outline btn-block" style="margin-top:10px" data-action="share-ref" '+(!invitation?'disabled':'')+'>'+icon('share')+' Invite via Telegram</button>'+
section('How referrals work')+'<div class="ref-steps"><div class="step"><span class="step-num">01</span><div><div class="step-title">Share your link</div><div class="step-desc">Your friend opens AFGLION through Telegram.</div></div></div><div class="step"><span class="step-num">02</span><div><div class="step-title">Friend joins and buys VIP</div><div class="step-desc">Their wallet is funded and the administrator approves their VIP purchase.</div></div></div><div class="step"><span class="step-num">03</span><div><div class="step-title">Commission credited</div><div class="step-desc">Your AFN wallet receives the configured commission once.</div></div></div></div>'+
section('Your referrals')+(data().referrals.length?'<div class="user-list">'+data().referrals.map(function(r){return '<div class="user-row">'+avatar(r)+'<div class="user-main"><strong>'+esc(r.name)+'</strong><small>Joined '+fmtDate(r.joinedAt)+'</small></div><div class="user-end">'+icon('check')+'</div></div>';}).join('')+'</div>':empty('users','No referrals yet','Friends who register through your link will appear here.'))+footer()+'</div>';}
function vip(){var u=user(),s=data().settings,req=data().vipRequest,plans=s.plans||{},p=activePlan();return '<div class="view">'+goldTitle('VIP membership.','Transparent plan details, daily claims and manual administrator approval.')+
'<div class="vip-hero"><div class="eyebrow">YOUR MEMBERSHIP</div><h2>Member.<br>Premium.</h2><p>Manage your status and reward schedule in one place.</p><div class="vip-current"><i></i>'+esc((u.vipTier||'free').toUpperCase())+' STATUS'+(u.vipUntil&&u.vipTier!=='free'?' · Until '+fmtDate(u.vipUntil):'')+'</div></div>'+
(p?'<div class="vip-progress">'+section('Your daily reward')+'<div class="plan-progress"><b>'+currency(p.dailyReward)+' / eligible day</b><small>'+n(u.vipDaysClaimed||0)+' claimed · '+n(p.days)+' scheduled days</small><button class="btn btn-primary btn-block" data-action="vip-claim" '+(!vipCanClaim()?'disabled':'')+'>'+(vipCanClaim()?'Claim today’s VIP reward':'Next VIP reward not ready')+'</button></div></div>':'')+
section('Available membership plans')+'<div class="tier-list">'+['free','gold','elite'].map(function(tier){if(tier==='free')return '<div class="tier"><div class="tier-top"><div class="tier-title">'+icon('shield')+' Essential</div><div class="tier-price">FREE</div></div><div class="tier-benefits"><div class="tier-feature">'+icon('check')+' Free daily check-in</div><div class="tier-feature">'+icon('check')+' Referral commissions on paid VIP</div></div></div>';
var v=plans[tier]||{},mine=u.vipTier===tier&&u.vipUntil>Date.now(),pending=req&&req.status==='pending'&&req.tier===tier;
return '<div class="tier '+(tier==='elite'?'premium':'')+'"><div class="tier-top"><div class="tier-title"><span class="action-icon">'+icon('crown')+'</span><span>'+esc(v.name||tier.toUpperCase())+'</span></div><div class="tier-price">'+currency(v.price)+'<small>'+n(v.days)+'-day membership</small></div></div><div class="plan-big"><b>'+currency(v.dailyReward)+'</b><span>scheduled per eligible day</span></div><div class="tier-benefits"><div class="tier-feature">'+icon('check')+' '+n(v.days)+' calendar-day reward schedule</div><div class="tier-feature">'+icon('check')+' Total scheduled: '+currency((v.dailyReward||0)*(v.days||0))+'</div><div class="tier-feature">'+icon('check')+' Admin reviews each purchase</div></div><button class="btn '+(mine?'btn-ghost':'btn-primary')+' btn-block" '+(mine||pending?'disabled':'data-action="vip-request" data-tier="'+tier+'"')+'>'+(mine?'Current plan':pending?'Awaiting admin approval':'Request '+esc(v.name||tier.toUpperCase()))+'</button></div>';}).join('')+'</div>'+
'<div class="alert">'+icon('info')+' VIP purchase requires approved wallet funds. Rewards are credited only when you claim an eligible day; missed claims are not accumulated. This is a high-risk rewards model, not guaranteed investment income.</div>'+footer()+'</div>';}
function wallet(){var u=user(),s=data().settings,items=data().transactions||[];return '<div class="view">'+goldTitle('Your wallet.','Track available AFN funds, submitted payments and payouts.')+hero()+
'<div class="wallet-actions"><button class="wallet-action" data-action="deposit"><span>'+icon('arrow')+'</span><b>Deposit</b><small>Manual approval</small></button><button class="wallet-action" data-action="withdraw"><span>'+icon('wallet')+'</span><b>Withdraw</b><small>Manual payout</small></button><button class="wallet-action" data-action="refresh"><span>'+icon('refresh')+'</span><b>Refresh</b><small>Get latest status</small></button></div>'+
'<div class="stats-row"><div class="stat-small"><div class="label">Deposited</div><div class="value">'+n(u.totalDeposited)+'</div></div><div class="stat-small"><div class="label">Withdrawn</div><div class="value">'+n(u.totalWithdrawn)+'</div></div><div class="stat-small"><div class="label">On hold</div><div class="value gold">'+n(u.pendingWithdraw)+'</div></div></div>'+
section('Manual payment history')+(items.length?'<div class="transaction-list">'+items.map(function(t){return '<div class="transaction-row"><div class="transaction-icon">'+icon(t.type==='deposit'?'arrow':'wallet')+'</div><div class="transaction-main"><strong>'+esc(t.type==='deposit'?'Deposit':'Withdrawal')+' · '+currency(t.amount)+'</strong><small>'+esc(t.method)+' · '+fmtDate(t.createdAt)+'</small><small>'+esc(t.status||'pending')+'</small></div><span class="badge '+(t.status==='rejected'?'red':'')+'">'+esc(t.status||'pending')+'</span>'+(t.type==='withdraw'&&t.status==='pending'?'<button class="mini-cancel" data-action="cancel-withdraw" data-id="'+esc(t.id)+'">Cancel</button>':'')+'</div>';}).join('')+'</div>':empty('wallet','No wallet activity','Deposits and withdrawals will show here once you submit a request.'))+
'<div class="alert">'+icon('shield')+' Deposits are credited only after verified manual approval. Withdrawals reserve available funds until approved, rejected or cancelled.</div>'+footer()+'</div>';}
function empty(ic,title,desc){return '<div class="blank-state"><div class="round-icon">'+icon(ic)+'</div><h3>'+esc(title)+'</h3><p>'+esc(desc)+'</p></div>';}
function profile(){var u=user();return '<div class="view">'+goldTitle('Your profile.','Your AFGLION account and wallet settings.')+
'<div class="profile-top">'+avatar(u,'profile-pic')+'<div><h2 class="profile-name">'+esc(u.name)+'</h2><div class="profile-handle">'+esc(u.username?'@'+u.username:'AFGLION Member')+'</div><div class="profile-id">ID '+esc(u.id)+'</div></div></div>'+
'<div class="profile-stats"><div class="profile-stat"><div class="value">'+n(u.balance)+'</div><div class="label">AFN balance</div></div><div class="profile-stat"><div class="value">'+n(u.referralCount)+'</div><div class="label">Referrals</div></div></div>'+
section('Account')+'<div class="settings-list"><button class="settings-item" data-action="edit-name"><span class="settings-icon">'+icon('edit')+'</span><span class="settings-text">Display name</span><span class="settings-trail">'+icon('arrow')+'</span></button><button class="settings-item" data-page="wallet"><span class="settings-icon">'+icon('wallet')+'</span><span class="settings-text">Wallet · Deposit / Withdraw</span><span class="settings-trail">'+icon('arrow')+'</span></button><button class="settings-item" data-page="vip"><span class="settings-icon">'+icon('crown')+'</span><span class="settings-text">VIP status</span><span class="settings-trail"><span class="badge">'+esc((u.vipTier||'free').toUpperCase())+'</span>'+icon('arrow')+'</span></button><button class="settings-item" data-action="history"><span class="settings-icon">'+icon('clock')+'</span><span class="settings-text">Earnings history</span><span class="settings-trail">'+icon('arrow')+'</span></button></div>'+
section('More')+'<div class="settings-list"><button class="settings-item" data-action="help"><span class="settings-icon">'+icon('info')+'</span><span class="settings-text">Help & information</span><span class="settings-trail">'+icon('arrow')+'</span></button><button class="settings-item" data-action="refresh"><span class="settings-icon">'+icon('refresh')+'</span><span class="settings-text">Refresh account</span><span class="settings-trail">'+icon('arrow')+'</span></button>'+(u.isAdmin?'<button class="settings-item" data-action="open-admin"><span class="settings-icon">'+icon('shield')+'</span><span class="settings-text">Admin console</span><span class="settings-trail">'+icon('arrow')+'</span></button>':'')+'</div>'+
'<div class="muted-note" style="text-align:center;margin-top:20px">Member since '+fmtDate(u.joinedAt)+'</div>'+footer()+'</div>';}
function footer(){return '<div class="footer-sign">✦ &nbsp; AFGLION MEMBERS CLUB &nbsp; ✦</div>';}

function render(){if(!state.data)state.data=demoData;var body=state.page==='home'?home():state.page==='referral'?referral():state.page==='vip'?vip():state.page==='wallet'?wallet():profile();root.className='app-shell'+(state.page==='admin'?' admin-shell':'');if(state.page==='admin'){renderAdmin();return;}root.innerHTML=header()+(state.demo?'<div class="alert" style="margin-top:0">Preview mode · Open through your Telegram bot after configuring Firebase to save real account data.</div>':'')+body+nav();}
function go(page){if(page==='admin'){if(!user().isAdmin){toast('Admin only');return;}state.page='admin';loadAdmin();return;}if(!['home','referral','vip','profile','wallet'].includes(page))return;state.page=page;render();window.scrollTo({top:0,behavior:'smooth'});try{tg&&tg.HapticFeedback&&tg.HapticFeedback.selectionChanged();}catch(e){}}
async function api(action,payload){var res=await fetch('/api/index?action='+encodeURIComponent(action),{method:payload?'POST':'GET',headers:{'Content-Type':'application/json','Authorization':state.token?'Bearer '+state.token:''},body:payload?JSON.stringify(payload):undefined});var json=await res.json().catch(function(){return {error:'Server unavailable'};});if(!res.ok)throw new Error(json.error||'Request failed');return json;}
async function refresh(){if(state.demo)return;var d=await api('me');state.data=d;render();}
async function init(){try{if(tg){tg.ready();tg.expand();tg.setHeaderColor('#090c12');tg.setBackgroundColor('#090c12');}}catch(e){}
  if(!tg||!tg.initData){state.demo=true;render();return;}
  state.demo=false;
  try{var response=await api('auth',{initData:tg.initData,startParam:(tg.initDataUnsafe&&tg.initDataUnsafe.start_param)||new URLSearchParams(location.search).get('tgWebAppStartParam')||''});state.token=response.token;sessionStorage.setItem('velora_session',state.token);await refresh();}
  catch(e){state.data=demoData;state.demo=true;render();document.querySelector('.alert').textContent='Setup or sign-in required: '+e.message+'. This preview does not save data.';}
}
async function run(action,payload,success){if(state.demo){toast('Preview mode · Live features require Telegram and Firebase setup');return null;}if(state.loading)return null;state.loading=true;try{var out=await api(action,payload);if(success)toast(success);await refresh();return out;}catch(e){toast(e.message);return null;}finally{state.loading=false;}}
function link(){var s=data().settings;return s.botUsername?'https://t.me/'+s.botUsername+'?startapp=ref_'+user().id:'';}
async function copyValue(value){try{await navigator.clipboard.writeText(value);toast('Copied to clipboard');}catch(e){var box=document.createElement('textarea');box.value=value;document.body.appendChild(box);box.select();document.execCommand('copy');box.remove();toast('Copied');}}
function modal(title,inner){closeModal();var el=document.createElement('div');el.className='modal-backdrop';el.id='modal-layer';el.innerHTML='<div class="modal" role="dialog" aria-modal="true"><div class="modal-header"><h2>'+title+'</h2><button class="close-modal" data-action="close-modal" aria-label="Close">×</button></div>'+inner+'</div>';document.body.appendChild(el);el.addEventListener('click',function(e){if(e.target===el)closeModal();});}
function closeModal(){var el=document.getElementById('modal-layer');if(el)el.remove();}
function historyModal(){var acts=data().activity||[];modal('Activity history',acts.length?'<div class="user-list" style="margin-top:18px">'+acts.map(function(a){return '<div class="user-row"><div class="action-icon">'+icon('bolt')+'</div><div class="user-main"><strong>'+esc(a.label)+'</strong><small>'+fmtDate(a.at)+'</small></div><div class="user-end">'+(a.amount>=0?'+':'')+n(a.amount)+' PTS</div></div>';}).join('')+'</div>':empty('clock','No activity yet','Your rewards and account changes will appear here.'));}
document.addEventListener('click',async function(e){var target=e.target.closest('[data-action],[data-page]');if(!target)return;if(target.dataset.page){go(target.dataset.page);return;}var action=target.dataset.action;
switch(action){

case 'deposit':paymentModal('deposit');break;
case 'withdraw':paymentModal('withdraw');break;
case 'vip-claim':await run('vipClaim',{},'VIP daily reward credited!');break;
case 'cancel-withdraw':if(confirm('Cancel this pending withdrawal and release the reserved AFN?'))await run('cancelWithdrawal',{requestId:target.dataset.id},'Withdrawal cancelled');break;
case 'admin-money-approve':await adminAction('reviewMoney',{requestId:target.dataset.id,approve:true});break;
case 'admin-money-reject':await adminAction('reviewMoney',{requestId:target.dataset.id,approve:false});break;
case 'claim':await run('claim',{},'Your daily reward has arrived!');break;
case 'notification':modal('Announcements','<div class="notice" style="margin-top:16px"><div class="notice-icon">'+icon('bell')+'</div><div><h3>Latest announcement</h3><p>'+esc(data().settings.announcement||'Welcome to AFGLION!')+'</p></div></div>');break;
case 'copy-ref':if(link())await copyValue(link());break;
case 'share-ref':if(link()){var url='https://t.me/share/url?url='+encodeURIComponent(link())+'&text='+encodeURIComponent('Join me on AFGLION!');if(tg&&tg.openTelegramLink)tg.openTelegramLink(url);else window.open(url,'_blank','noopener,noreferrer');}break;
case 'vip-request':var tier=target.dataset.tier,p=(data().settings.plans||{})[tier];modal('Request VIP membership','<p class="body-sub">'+esc(p&&p.name||tier.toUpperCase())+' costs '+currency(p&&p.price||0)+'. The administrator reviews this purchase and deducts its price from your available AFN wallet after approval. Deposit first if needed.</p><button class="btn btn-primary btn-block" data-action="confirm-vip" data-tier="'+esc(tier)+'">Submit VIP request</button>');break;
case 'confirm-vip':var vip=target.dataset.tier;closeModal();await run('vipRequest',{tier:vip},'VIP request sent for review');break;
case 'edit-name':modal('Edit display name','<form id="name-form"><label class="form-label">Your name</label><input class="field" id="new-name" maxlength="48" minlength="2" value="'+esc(user().name)+'" required><button class="btn btn-primary btn-block" style="margin-top:16px">Save changes</button></form>');break;
case 'history':historyModal();break;
case 'help':modal('Help & information','<p class="body-sub">AFGLION is a members club experience. Earn points with daily check-ins and referrals. VIP access is manually approved by the club administrator.</p><div class="alert">Points are in-app membership rewards, not cash or withdrawable funds. VIP requests do not constitute a payment.</div>');break;
case 'refresh':try{await refresh();toast('Account refreshed');}catch(ex){toast(ex.message);}break;
case 'open-admin':go('admin');break;
case 'close-modal':closeModal();break;
case 'back-admin':state.page='profile';render();break;
case 'admin-tab':state.adminTab=target.dataset.tab;renderAdmin();break;
case 'admin-user':openUserModal(target.dataset.id);break;
case 'admin-approve':await adminAction('approveVip',{requestId:target.dataset.id});break;
case 'admin-reject':await adminAction('rejectVip',{requestId:target.dataset.id});break;
case 'admin-save-settings':saveAdminSettings();break;
case 'admin-save-user':saveAdminUser();break;
}});

function paymentModal(type){var s=data().settings,deposit=type==='deposit';modal(deposit?'Request deposit':'Request withdrawal',
'<p class="body-sub">'+esc(deposit?s.depositInstructions:s.payoutInstructions)+'</p>'+
'<form id="money-form" data-type="'+type+'"><label class="form-label">Amount in AFN (minimum '+n(deposit?s.minDeposit:s.minWithdraw)+')</label><input class="field" id="money-amount" type="number" min="'+(deposit?s.minDeposit:s.minWithdraw)+'" max="1000000" step="1" placeholder="Amount" required>'+
'<label class="form-label">Payment method</label><select class="field" id="money-method" required><option value="Hawala">Hawala</option><option value="Bank transfer">Bank transfer</option><option value="Cash agent">Cash agent</option><option value="Mobile wallet">Mobile wallet</option><option value="Other">Other</option></select>'+
'<label class="form-label">'+(deposit?'Payment reference / receipt number':'Recipient phone, account or payout details')+'</label><textarea class="field" id="money-details" minlength="5" maxlength="300" placeholder="'+(deposit?'Provide a real payment reference; no automatic payment is made':'Include your correct recipient information')+'" required></textarea>'+
'<div class="alert">'+(deposit?'Submitting a deposit request does not credit the wallet. Admin confirms receipt first.':'Withdrawn AFN is reserved immediately and manually paid after approval.')+'</div><button class="btn btn-primary btn-block" style="margin-top:14px">Submit '+(deposit?'deposit':'withdrawal')+' request</button></form>');}

document.addEventListener('submit',async function(e){if(e.target.id==='money-form'){e.preventDefault();var type=e.target.dataset.type;var amount=Number(document.getElementById('money-amount').value);var method=document.getElementById('money-method').value;var details=document.getElementById('money-details').value.trim();closeModal();await run('moneyRequest',{type:type,amount:amount,method:method,details:details},'Request submitted for manual review');state.page='wallet';render();return;}if(e.target.id==='name-form'){e.preventDefault();var name=document.getElementById('new-name').value.trim();if(name.length<2)return toast('Name is too short');closeModal();await run('profileUpdate',{name:name},'Name updated');}});
async function loadAdmin(){if(state.demo){toast('Admin requires verified Telegram sign-in');state.page='profile';render();return;}try{state.admin=await api('adminData');renderAdmin();}catch(e){toast(e.message);state.page='profile';render();}}

function adminTabs(){return '<div class="admin-tabs">'+[['overview','Overview'],['users','Members'],['requests','VIP'],['money','Payments'],['settings','Settings']].map(function(t){return '<button class="admin-tab '+(state.adminTab===t[0]?'active':'')+'" data-action="admin-tab" data-tab="'+t[0]+'">'+t[1]+'</button>';}).join('')+'</div>';}
function adminUserRows(users){return users.length?users.map(function(u){return '<div class="admin-row"><div style="min-width:0"><strong>'+esc(u.name||'Member')+'</strong> '+(u.banned?'<span class="badge red">BANNED</span>':'')+'<small>ID '+esc(u.id)+' · '+currency(u.balance)+' · '+esc(u.vipTier||'free')+'</small></div><button class="btn btn-ghost btn-small" data-action="admin-user" data-id="'+esc(u.id)+'">Manage</button></div>';}).join(''):empty('users','No members found','No matching members.');}
function adminNumber(label,id,value,min,max){return '<div><label class="form-label">'+esc(label)+'</label><input class="field" id="'+id+'" type="number" min="'+min+'" max="'+max+'" step="1" value="'+n(value).replace(/,/g,'')+'" required></div>';}
function renderAdmin(){var a=state.admin;if(!a){root.innerHTML=header()+'<div class="body-sub">Loading admin...</div>';return;}
 var tab=state.adminTab,html='<header class="topbar"><div class="brand-wrap"><span class="brand-mark">A</span><div><div class="brand-name">AFGLION ADMIN</div><div class="brand-kicker">CONTROL CENTER</div></div></div><button class="round-button" data-action="back-admin" aria-label="Close admin">'+icon('logout')+'</button></header><div class="view">'+goldTitle('Control center.','Verified admin tools: VIP, referral rates, deposits and withdrawals.')+adminTabs();
 if(tab==='overview')html+='<div class="admin-quick"><div class="admin-card"><b>'+n(a.stats.members)+'</b><small>Members</small></div><div class="admin-card"><b>'+n(a.stats.vip)+'</b><small>Active VIP</small></div><div class="admin-card"><b>'+n(a.stats.pending)+'</b><small>Pending reviews</small></div><div class="admin-card"><b>'+n(a.stats.points)+'</b><small>AFN in user wallets</small></div></div>'+section('Newest members')+adminUserRows(a.users.slice(0,6));
 if(tab==='users')html+='<input id="admin-search" class="field" placeholder="Search name or Telegram ID" aria-label="Search members"><div id="admin-users">'+adminUserRows(a.users)+'</div>';
 if(tab==='requests')html+=a.requests.length?a.requests.map(function(req){return '<div class="admin-row"><div><strong>'+esc(req.name||req.userId)+'</strong> <span class="badge">'+esc(req.tier.toUpperCase())+'</span><small>'+currency(req.price)+' · '+fmtDate(req.createdAt)+'</small></div><div class="mini-actions"><button class="btn btn-primary btn-small" data-action="admin-approve" data-id="'+esc(req.id)+'">Approve</button><button class="btn btn-ghost btn-small" data-action="admin-reject" data-id="'+esc(req.id)+'">Reject</button></div></div>';}).join(''):empty('check','No VIP requests','You have no VIP purchases to review.');
 if(tab==='money')html+=(a.moneyRequests||[]).length?a.moneyRequests.map(function(req){return '<div class="payment-review"><div class="review-header"><b>'+esc(req.type==='deposit'?'⬇ Deposit':'⬆ Withdrawal')+' · '+currency(req.amount)+'</b><span class="badge">PENDING</span></div><p><b>'+esc(req.name)+'</b> · ID '+esc(req.userId)+'</p><p>Method: '+esc(req.method)+'</p><p>Reference / Details: '+esc(req.details)+'</p><small>'+fmtDate(req.createdAt)+'</small><div class="review-actions"><button class="btn btn-primary btn-small" data-action="admin-money-approve" data-id="'+esc(req.id)+'">Approve</button><button class="btn btn-ghost btn-small" data-action="admin-money-reject" data-id="'+esc(req.id)+'">Reject</button></div></div>';}).join(''):empty('check','No payment requests','Deposits and withdrawals awaiting review will appear here.');
 if(tab==='settings'){var st=a.settings,gs=st.plans.gold,es=st.plans.elite;
 html+='<label class="form-label">Announcement</label><textarea id="admin-announcement" class="field" maxlength="350">'+esc(st.announcement||'')+'</textarea>'+
 '<div class="inline-fields">'+adminNumber('Free check-in (AFN)','admin-daily',st.dailyBonus,0,1000)+adminNumber('VIP referral %','admin-referral',st.referralPercent,0,50)+'</div>'+
 section('Gold VIP')+'<div class="inline-fields">'+adminNumber('Price (AFN)','gold-price',gs.price,1,1000000)+adminNumber('Daily (AFN)','gold-daily',gs.dailyReward,0,100000)+'</div>'+adminNumber('Duration (days)','gold-days',gs.days,1,365)+
 section('Elite VIP')+'<div class="inline-fields">'+adminNumber('Price (AFN)','elite-price',es.price,1,1000000)+adminNumber('Daily (AFN)','elite-daily',es.dailyReward,0,100000)+'</div>'+adminNumber('Duration (days)','elite-days',es.days,1,365)+
 section('Manual payments')+'<div class="inline-fields">'+adminNumber('Minimum deposit','admin-min-deposit',st.minDeposit,1,100000)+adminNumber('Minimum withdraw','admin-min-withdraw',st.minWithdraw,1,100000)+'</div>'+
 '<label class="form-label">Deposit instructions</label><textarea class="field" id="admin-deposit-inst" maxlength="500">'+esc(st.depositInstructions||'')+'</textarea>'+
 '<label class="form-label">Payout instructions</label><textarea class="field" id="admin-payout-inst" maxlength="500">'+esc(st.payoutInstructions||'')+'</textarea>'+
 '<label class="form-label">Bot username (without @)</label><input class="field" id="admin-bot" value="'+esc(st.botUsername||'Afglionbot')+'"><button class="btn btn-primary btn-block" style="margin-top:20px" data-action="admin-save-settings">Save all settings</button>';
 }
 root.className='app-shell admin-shell';root.innerHTML=html+footer()+'</div>';
 var search=document.getElementById('admin-search');if(search)search.addEventListener('input',function(){var q=search.value.toLowerCase().trim();document.getElementById('admin-users').innerHTML=adminUserRows(a.users.filter(function(u){return ((u.name||'')+' '+(u.username||'')+' '+u.id).toLowerCase().includes(q);}));});
 window.scrollTo({top:0,behavior:'smooth'});
}
function openUserModal(id){var u=state.admin.users.find(function(x){return x.id===id;});if(!u)return;modal('Manage member','<div class="user-row" style="margin-top:16px">'+avatar(u)+'<div class="user-main"><strong>'+esc(u.name)+'</strong><small>ID '+esc(u.id)+'</small></div></div><label class="form-label">VIP access</label><select class="field" id="user-tier"><option value="free" '+(u.vipTier==='free'?'selected':'')+'>Free</option><option value="gold" '+(u.vipTier==='gold'?'selected':'')+'>Gold</option><option value="elite" '+(u.vipTier==='elite'?'selected':'')+'>Elite</option></select><label class="form-label">Credit AFN (0 to skip)</label><input class="field" id="user-points" type="number" min="0" max="100000" step="1" value="0"><label class="form-label">Account status</label><select class="field" id="user-ban"><option value="false" '+(!u.banned?'selected':'')+'>Active</option><option value="true" '+(u.banned?'selected':'')+'>Banned</option></select><button class="btn btn-primary btn-block" style="margin-top:20px" data-action="admin-save-user" data-id="'+esc(u.id)+'">Save changes</button>');}
async function saveAdminUser(){var el=document.querySelector('[data-action="admin-save-user"]');if(!el)return;await adminAction('updateUser',{userId:el.dataset.id,tier:document.getElementById('user-tier').value,addPoints:Number(document.getElementById('user-points').value),banned:document.getElementById('user-ban').value==='true'});}
function getNum(id){return Number(document.getElementById(id).value);}
async function saveAdminSettings(){await adminAction('saveSettings',{
 announcement:document.getElementById('admin-announcement').value,dailyBonus:getNum('admin-daily'),referralPercent:getNum('admin-referral'),
 minDeposit:getNum('admin-min-deposit'),minWithdraw:getNum('admin-min-withdraw'),
 botUsername:document.getElementById('admin-bot').value.trim().replace(/^@/,''),
 depositInstructions:document.getElementById('admin-deposit-inst').value,payoutInstructions:document.getElementById('admin-payout-inst').value,
 plans:{gold:{price:getNum('gold-price'),dailyReward:getNum('gold-daily'),days:getNum('gold-days')},elite:{price:getNum('elite-price'),dailyReward:getNum('elite-daily'),days:getNum('elite-days')}}
});}
async function adminAction(type,payload){if(state.loading)return;state.loading=true;try{await api('adminAction',Object.assign({type:type},payload));closeModal();state.admin=await api('adminData');await refresh();state.page='admin';renderAdmin();toast('Changes saved');}catch(e){toast(e.message);}finally{state.loading=false;}}

init();
})();
